export const notificationsData = [
  {
    id: 1,
    title: "Server Down",
    message: "Main API server is not responding",
    type: "critical",
    time: "2 min ago",
  },
  {
    id: 2,
    title: "New User Registered",
    message: "A new user signed up successfully",
    type: "success",
    time: "10 min ago",
  },
  {
    id: 3,
    title: "High Memory Usage",
    message: "IoT device memory usage is above 80%",
    type: "warning",
    time: "30 min ago",
  },
  {
    id: 1,
    title: "Server Down",
    message: "Main API server is not responding",
    type: "critical",
    time: "2 min ago",
  },
  {
    id: 2,
    title: "New User Registered",
    message: "A new user signed up successfully",
    type: "success",
    time: "10 min ago",
  },
  {
    id: 3,
    title: "High Memory Usage",
    message: "IoT device memory usage is above 80%",
    type: "warning",
    time: "30 min ago",
  },
  {
    id: 1,
    title: "Server Down",
    message: "Main API server is not responding",
    type: "critical",
    time: "2 min ago",
  },
  {
    id: 2,
    title: "New User Registered",
    message: "A new user signed up successfully",
    type: "success",
    time: "10 min ago",
  },
  {
    id: 3,
    title: "High Memory Usage",
    message: "IoT device memory usage is above 80%",
    type: "warning",
    time: "30 min ago",
  },
  {
    id: 1,
    title: "Server Down",
    message: "Main API server is not responding",
    type: "critical",
    time: "2 min ago",
  },
  {
    id: 2,
    title: "New User Registered",
    message: "A new user signed up successfully",
    type: "success",
    time: "10 min ago",
  },
  {
    id: 3,
    title: "High Memory Usage",
    message: "IoT device memory usage is above 80%",
    type: "warning",
    time: "30 min ago",
  },
  {
    id: 1,
    title: "Server Down",
    message: "Main API server is not responding",
    type: "critical",
    time: "2 min ago",
  },
  {
    id: 2,
    title: "New User Registered",
    message: "A new user signed up successfully",
    type: "success",
    time: "10 min ago",
  },
  {
    id: 3,
    title: "High Memory Usage",
    message: "IoT device memory usage is above 80%",
    type: "warning",
    time: "30 min ago",
  },
  {
    id: 1,
    title: "Server Down",
    message: "Main API server is not responding",
    type: "critical",
    time: "2 min ago",
  },
  {
    id: 2,
    title: "New User Registered",
    message: "A new user signed up successfully",
    type: "success",
    time: "10 min ago",
  },
  {
    id: 3,
    title: "High Memory Usage",
    message: "IoT device memory usage is above 80%",
    type: "warning",
    time: "30 min ago",
  },
  {
    id: 1,
    title: "Server Down",
    message: "Main API server is not responding",
    type: "critical",
    time: "2 min ago",
  },
  {
    id: 2,
    title: "New User Registered",
    message: "A new user signed up successfully",
    type: "success",
    time: "10 min ago",
  },
  {
    id: 3,
    title: "High Memory Usage",
    message: "IoT device memory usage is above 80%",
    type: "warning",
    time: "30 min ago",
  },
  {
    id: 1,
    title: "Server Down",
    message: "Main API server is not responding",
    type: "critical",
    time: "2 min ago",
  },
  {
    id: 2,
    title: "New User Registered",
    message: "A new user signed up successfully",
    type: "success",
    time: "10 min ago",
  },
  {
    id: 3,
    title: "High Memory Usage",
    message: "IoT device memory usage is above 80%",
    type: "warning",
    time: "30 min ago",
  },
  {
    id: 1,
    title: "Server Down",
    message: "Main API server is not responding",
    type: "critical",
    time: "2 min ago",
  },
  {
    id: 2,
    title: "New User Registered",
    message: "A new user signed up successfully",
    type: "success",
    time: "10 min ago",
  },
  {
    id: 3,
    title: "High Memory Usage",
    message: "IoT device memory usage is above 80%",
    type: "warning",
    time: "30 min ago",
  },
  {
    id: 1,
    title: "Server Down",
    message: "Main API server is not responding",
    type: "critical",
    time: "2 min ago",
  },
  {
    id: 2,
    title: "New User Registered",
    message: "A new user signed up successfully",
    type: "success",
    time: "10 min ago",
  },
  {
    id: 3,
    title: "High Memory Usage",
    message: "IoT device memory usage is above 80%",
    type: "warning",
    time: "30 min ago",
  },
];
